invetronic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


urlpatterns = [
    url(r'^', include('authentication.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^tickets/', include('tickets.urls')),
]


# Change admin site title
admin.site.site_header = _(settings.ADMIN_SITE_HEADER)
admin.site.site_title = _(settings.ADMIN_SITE_TITLE)

tickets/urls.py
from django.conf.urls import url
from tickets import views


urlpatterns = [
    # ex: /inventario/2/printmachine/
    url(r'^$', views.IncidentListView.as_view(), name='incident_list'),
    url(r'^new$', views.IncidentCreate.as_view(success_url="/tickets/"), name='incident_new', ),
    #url(r'^machine/(?P<pk>[0-9]+)/$', views.MachineDetail.as_view(), name='machine_detail'),
    
]

tickets/models.py
from django.db import models

from authentication.models import User
from inventario.models import Machine

# Create your models here.
class Incident(models.Model):
    class Meta:
        verbose_name = ("Incidente")

    BUG_STATUS = (
        ('O','Abierto'),
        ('C','Cerrado'),
    )

    BUG_SEVERITY = (
        ('5','Grave'),
        ('4','Importante'),
        ('3','Medio'),
        ('2','Simple'),
        ('1','Mínimo'),
        ('0','Sin Clasificar'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="usuario", related_name='usuario', blank=False, null=False)
    machine = models.ForeignKey(Machine, on_delete=models.CASCADE, verbose_name="maquina", related_name='maquina', blank=False, null=False)
    overview = models.CharField(max_length=100, verbose_name="resumen", blank=False, null=False)
    description = models.TextField(max_length=1500, verbose_name="descripción", blank=False, null=False)

    remote_diagnosis = models.TextField(max_length=1500, verbose_name="diagnóstico remoto", blank=True, null=True)
    phone_diagnosis = models.TextField(max_length=1500, verbose_name="diagnóstico teléfono", blank=True, null=True)
    visit_diagnosis = models.TextField(max_length=1500, verbose_name="diagnóstico visita", blank=True, null=True)

    creation_time = models.DateTimeField(auto_now_add=True,verbose_name="fecha de creacion",blank=False, null=False)

    severity = models.CharField(max_length=1,choices=BUG_SEVERITY,default='0',verbose_name="gravedad", blank=False, null=False)
    status = models.CharField(max_length=1,choices=BUG_STATUS,default='O',verbose_name="estado", blank=True, null=True)

    def __str__(self):
        return self.overview

    def __unicode__(self):
        return self.overview

tickets/views.py
from django.shortcuts import render
from tickets.models import Incident
from inventario.models import Machine

from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple


from django.views.generic.list import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.utils import timezone

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.core.urlresolvers import reverse_lazy

from common import utils
# Create your views here.

class IncidentForm(forms.ModelForm):

    #machine = forms.TypedChoiceField(choices=Machine.objects.all(), coerce=int)

    class Meta:
        model = Incident
        fields = ['overview', 'description','machine']

    def __init__(self,user, *args, **kwargs):
        super(IncidentForm, self).__init__(*args, **kwargs)
        machine_size = (Machine.objects.filter(company=user.company.pk).count(),10)[Machine.objects.filter(company=user.company.pk).count()>10]
        #self.fields['machine'] = forms.ModelChoiceField(queryset=Machine.objects.filter(company=user.company.pk))
        self.fields['machine'] = forms.ModelChoiceField(queryset=Machine.objects.filter(company=user.company.pk),
            widget=FilteredSelectMultiple("verbose name", is_stacked=False, attrs={'size':machine_size}), empty_label="MÁQUINA")

"""  class Meta(object):
    model = Account
  parent = forms.ModelChoiceField(queryset=Machine.objects.filter(pk=))
"""
class IncidentCreate(CreateView):
    model = Incident
    form_class = IncidentForm
    success_url = reverse_lazy('books_cbv:book_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(IncidentCreate, self).form_valid(form)

    def get_form_kwargs(self):
        kwargs = super(IncidentCreate, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(IncidentCreate, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['page_title'] = 'Nuevo Incidente'
        context['breadcrumbs'] = utils.get_breadcrumbs_from_url(self.request.get_full_path())
        success_url = reverse_lazy('incident_list')  
        return context


class IncidentListView(ListView):

    model = Incident

    def get_context_data(self, **kwargs):
        context = super(IncidentListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        context['page_title'] = 'Tickets'
        context['breadcrumbs'] = utils.get_breadcrumbs_from_url(self.request.get_full_path())
        if self.request.user.is_superuser:
            context['object_list'] = Incident.objects.all()
        elif self.request.user.tipo_usuario == 'CLIENTE' or self.request.user.tipo_usuario == 'CLIENTE_ADMIN':
            context['object_list'] = Incident.objects.filter(user__company=self.request.user.company.pk)
        elif self.request.user.tipo_usuario == 'TECNICO': # falta implementar logica para buscar machinas asignadas a los tickets
            context['object_list'] = Incident.objects.filter(user__company=self.request.user.company.pk)
        else:
            context['object_list'] = []
        #print(self.request.__dict__)
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(IncidentListView, self).dispatch(*args, **kwargs)

tickets/templates/tickets/incident_form.html
{% extends "base.html" %}
{% load i18n static bootstrap_admin_template_tags %}

{% block buttons %}
    <a title="Crear" class="btn btn-info btn-sm" href='/tickets/new'><span class="fa fa-plus"> Crear</span>
{% endblock %}

{% block content %}
              <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              Nuevo Incidente
                          </header>
                          	<form method="post">{% csrf_token %}

              				{{ form.overview|add_class:'form-control'|placeholder:form.overview.label }}
                      {{ form.description|add_class:'form-control'|placeholder:form.description.label }}
                      {{ form.machine|add_class:'form-control'|placeholder:form.machine.label }}
							    <!--{{ form.as_p }} -->
							    <input type="submit" value="Submit" />
							</form>
                      </section>
                  </div>
              </div>
              <!-- page end-->

{% endblock %}

tickets/templates/tickets/incident_list.html
{% extends "base.html" %}

{% block buttons %}
    <a title="Crear" class="btn btn-info btn-sm" href='/tickets/new'><span class="fa fa-plus"> Crear</span>
{% endblock %}

{% block content %}
              <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              Incidentes
                          </header>
                          
                          <table class="table table-striped table-advance table-hover" style="font-size: smaller;">
                           <tbody>
                              <tr>
                                {% if user.is_active and user.is_staff %}
                                 <th><i class="fa fa-industry"></i> Compañía</th>
                                {% endif %}
                                 <th><i class="glyphicon glyphicon-tag"></i> Resumen</th>
                                 <th><i class="fa fa-desktop"></i> Maquina</th>
                                 <th><i class="fa fa-exclamation-triangle"></i> Gravedad</th>
                                 <th><i class="glyphicon glyphicon-eye-open"></i> Estado</th>
                                 <th><i class="fa fa-user"></i> Usuario</th>
                                 <th></th>
                              </tr>
								{% for incident in object_list %}
                              <tr>
                                {% if user.is_active and user.is_staff %}
                                 <td>{{ incident.user.company|default_if_none:"--" }}</td>
                                {% endif %}
                                 <td>{{ incident.overview|default_if_none:"--" }}</td>
                                 <td>{{ incident.creation_time|default_if_none:"--" }}</td>
                                 <td>{{ incident.get_severity_display|default_if_none:"--" }}</td>
                                 <td>{{ incident.get_status_display|default_if_none:"--" }}</td>
                                 <td>{{ incident.user|default_if_none:"--" }}</td>
                                 <td>
                                  <div class="btn-group">
                                    <a title="Imprimir" class="btn btn-info btn-sm" href='/inventario/{{ incident.id }}/printincident'><span class="fa fa-print"></span>
                                    </a>
                                    <a title="Imprimir" class="btn btn-info btn-sm" href='/inventario/incident/{{ incident.id }}'><span class="fa fa-eye"></span>
                                    </a>
                                  </div>
                                 </td>
                              </tr>
								{% empty %}
                              <tr>
                                 <td>No se encontraron resultados</td>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                                 <td></td>
                              </tr>
								{% endfor %}                         
                           </tbody>
                        </table>
                      </section>
                  </div>
              </div>
              <!-- page end-->

{% endblock %}